# Generated by Django 5.2.7 on 2025-11-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main_api', '0003_attachment_storage_id_chat_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
